image: nvidia/cuda:11.8.0-devel-ubuntu22.04

stages:
  - build

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - export TZ=Europe/Berlin
  - apt-get update && apt-get -y install cmake
build:
  stage: build
  script:
    - mkdir cmake-build && cd cmake-build
    - cmake ..
    - make MCML -j
  artifacts:
    paths:
      - cmake-build/
  rules:
      - if: $CI_COMMIT_BRANCH == "develop" || $CI_PIPELINE_SOURCE == "merge_request_event"
