name: Build, Test & Install

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout project
      uses: actions/checkout@v4.1.7
    - name: Install apt dependencies
      run: |
        apt update && apt install cmake -y
    - name: Build project
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr ..
        make all -j
        make package -j
        dpkg -i MCML*.deb
    - name: Build and install DEB package
      run: |
        make package -j
        dpkg -i MCML*.deb
    - name: Install application
      run: |
        make install
