name: Build, Test & Install

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    strategy:
      matrix:
        os: [self-hosted]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout project
      uses: actions/checkout@v4.1.7
    - name: Build & install
      run: |
        docker build -t mcml:github .
